# Generated by Django 4.2 on 2023-05-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='guest',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
