# Generated by Django 4.2 on 2023-05-15 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_orderitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinstance',
            name='name',
        ),
    ]
