# Generated by Django 4.2 on 2023-06-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_order_options_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'отзыв', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.AddField(
            model_name='category',
            name='add_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Доп название'),
        ),
    ]
